<?php
// auto-generated by sfViewConfigHandler
// date: 2011/07/12 16:24:24
$context  = $this->getContext();
$response = $context->getResponse();

if ($this->actionName.$this->viewName == 'kmc1Success')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'varpartnerlistSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'supportSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'helpSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'kmc2helpSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'kmc1Success')
{
  $this->setDecoratorTemplate('kmc1layout'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Kaltura - Open Source Video Platform', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Kaltura homepage', false, false);
  $response->addMeta('keywords', 'production, shows, talent, discover, contribute, share, enhance, first open source video platform, video editing, media collaboration, online video, movie, wikimentaries, wiki', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('verify-v1', 'JIjZEB+ZCdDyAw49II0fIpcLfFc40M9EzXEY5/Tva68=', false, false);

  $response->addStylesheet('/lib/css/kmc1modal', '', array ());
  $response->addStylesheet('/lib/css/kmc1', '', array ());
  $response->addJavascript('jqkaltura.js');
  $response->addJavascript('/lib/js/kmc1modal');
  $response->addJavascript('/lib/js/common');
  $response->addJavascript('/lib/js/functions.js');
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js');
}
else if ($templateName.$this->viewName == 'varpartnerlistSuccess')
{
  $this->setDecoratorTemplate('kmc1layout'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Kaltura - Open Source Video Platform', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Kaltura homepage', false, false);
  $response->addMeta('keywords', 'production, shows, talent, discover, contribute, share, enhance, first open source video platform, video editing, media collaboration, online video, movie, wikimentaries, wiki', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('verify-v1', 'JIjZEB+ZCdDyAw49II0fIpcLfFc40M9EzXEY5/Tva68=', false, false);

  $response->addStylesheet('/lib/css/kmc1modal', '', array ());
  $response->addStylesheet('/lib/css/kmc1', '', array ());
  $response->addJavascript('jqkaltura.js');
  $response->addJavascript('/lib/js/kmc1modal');
  $response->addJavascript('/lib/js/common');
  $response->addJavascript('/lib/js/functions.js');
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js');
}
else if ($templateName.$this->viewName == 'supportSuccess')
{
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Kaltura - Open Source Video Platform', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Kaltura homepage', false, false);
  $response->addMeta('keywords', 'production, shows, talent, discover, contribute, share, enhance, first open source video platform, video editing, media collaboration, online video, movie, wikimentaries, wiki', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('verify-v1', 'JIjZEB+ZCdDyAw49II0fIpcLfFc40M9EzXEY5/Tva68=', false, false);

  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js');
}
else if ($templateName.$this->viewName == 'helpSuccess')
{
  $this->setDecoratorTemplate('helplayout'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Kaltura - Open Source Video Platform', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Kaltura homepage', false, false);
  $response->addMeta('keywords', 'production, shows, talent, discover, contribute, share, enhance, first open source video platform, video editing, media collaboration, online video, movie, wikimentaries, wiki', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('verify-v1', 'JIjZEB+ZCdDyAw49II0fIpcLfFc40M9EzXEY5/Tva68=', false, false);

  $response->addStylesheet('/lib/css/kmc', '', array ());
}
else if ($templateName.$this->viewName == 'kmc2helpSuccess')
{
  $this->setDecoratorTemplate('helplayout'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Kaltura - Open Source Video Platform', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Kaltura homepage', false, false);
  $response->addMeta('keywords', 'production, shows, talent, discover, contribute, share, enhance, first open source video platform, video editing, media collaboration, online video, movie, wikimentaries, wiki', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('verify-v1', 'JIjZEB+ZCdDyAw49II0fIpcLfFc40M9EzXEY5/Tva68=', false, false);

  $response->addStylesheet('/lib/css/kmc', '', array ());
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js');
}
else
{
  if (!$context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('kmclayout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Kaltura - Open Source Video Platform', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Kaltura homepage', false, false);
  $response->addMeta('keywords', 'production, shows, talent, discover, contribute, share, enhance, first open source video platform, video editing, media collaboration, online video, movie, wikimentaries, wiki', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('verify-v1', 'JIjZEB+ZCdDyAw49II0fIpcLfFc40M9EzXEY5/Tva68=', false, false);

  $response->addStylesheet('/lib/css/modal', '', array ());
  $response->addStylesheet('/lib/css/kmc', '', array ());
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js');
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js');
  $response->addJavascript('/lib/js/modal.js');
  $response->addJavascript('/lib/js/scripts.js');
}

